### ISSUE TITLE
Can you support using a proxy?

### ISSUE THREAD

**Issue by SiriusXT** [soulsands/trilium-chat#1]
Can you support using a proxy? I need to use a proxy to access chatgpt

**Comment by soulsands** [comment]
是要直接调用你的转发地址吗？可以在源码里替换一下这个地址 `https://api.openai.com/v1/chat/completions`。
后面会加一个配置项

**Comment by SiriusXT** [comment]
是需要代理访问

**Comment by soulsands** [comment]
https://github.com/chatanywhere/GPT_API_free 可以试下这个项目的地址，接口换成 https://api.chatanywhere.com.cn/v1/chat/completions， 可能有风险，我没试过
