### ISSUE TITLE
Ollama Support

### ISSUE THREAD

**Issue by TheOneValen** [soulsands/trilium-chat#13]
I would like to suggest to support https://github.com/jmorganca/ollama for a fully selfhosted experience.

**Comment by supermayx** [comment]
Can't agree more!

**Comment by Oaklight** [comment]
You can use [One-API](https://github.com/songquanpeng/one-api/) as a redirect and all-in-one proxy to many llm services including ollama. Just change the "option" note to the compatible URL and use the One-API key instead. Opt for your favorite model as well.

**Comment by TheOneValen** [comment]
ollama now has an openapi compatible api endpoint I will try that when I get the time. Is this addon still actively developed?

**Comment by Oaklight** [comment]
I can still use it today. But it's just a piece of script, not much fancy stuff. I'm able to use OneAPI as a bridge to use different endpoints from various API providers.

**Comment by perfectra1n** [comment]
Completed in #17 and now available for download.

**Comment by Oaklight** [comment]
> @Oaklight would you mind showing how you're using OneAPI to forward traffic to Ollama? I would love to include it in the README as well, and it sounds super cool.

Ollama is officially supported by OneAPI. And OneAPI API service is OpenAI compatible. 
You should be able to see a "channel/渠道" page.  Ollama is there in the dropdown menu when you add a new channel. Here is the screenshot of my self-hosted service. The system language has Chinese and English as options on dockerhub:
- Github: https://github.com/songquanpeng/one-api
- Chinese version: justsong/one-api
- English version: justsong/one-api-en
![image](https://github.com/soulsands/trilium-chat/assets/13076552/814d6720-162a-4115-ad8b-d2050fa824df)
