### ISSUE TITLE
{{activeNote}} isn't able to load any text with styles

### ISSUE THREAD

**Issue by Lolabird** [soulsands/trilium-chat#2]
Hi! First off cool plugin!

I've been playing around with the plugin today and noticed that the prompts with {{activeNote}} won't load any notes into the chat that have any kind of styling on them - header, bullet points, etc. It also doesn't support webView notes. I may do more tests later to see if any other note types have issues.

**Comment by soulsands** [comment]
Hi there! Thank you for trying out the plugin and sharing your feedback.

Regarding your issue, {{activeNote}} only supports text/code and text note is not properly parsed for now. I apologize for any inconvenience this may cause.

BTW, could you help me imporve expressions of the document, user interface, among other things? I'm not confident in my knowledge of the correct terminology as a non-native speaker.

**Comment by Lolabird** [comment]
Thanks for replying! And sure, I'll give the docs a look and do a pull request if I find anything that needs fixing. As far as code, I'm still learning, so I'll probably just open issues if I find anything for now.

**Comment by soulsands** [comment]
Thanks!  And the {{activeNote}} is handled with a tradeoff which expained in the document. Any suggestion would be appreciated. You have a good sense of design.

**Comment by Lolabird** [comment]
I just saw that fix today! It's working great so far! I'll keep testing it, but I'll close this issue out for now. And thanks for the compliment :smiley:
