### ISSUE TITLE
Expand set up documentation?

### ISSUE THREAD

**Issue by mascooler** [soulsands/trilium-chat#4]
Hi - really keen to check out this functionality in Trilium. 

Have been working on this this afternoon but struggling to follow set up steps - possible to add more detail?

Have tried 
-copying trilium-chat.js into new note - adds the prompt and option child notes but don't work on reload 
- copying main.js into note (after searching for a while - located in "src" folder), doesn't add the prompt and option notes 
- copying the entire zip folder (after changing nginx conf to increase upload file size)

With no success on getting up and running to now. 

Would you be able to detail more steps on initial set up? Thanks - mc

**Comment by soulsands** [comment]
I apologize for the confusion. I renamed the file from main.js to trilium-chat.js, but forgot to update the documentation. You can download the latest file from https://github.com/soulsands/trilium-chat/releases. Thank you for the feedback.

**Comment by mascooler** [comment]
Thanks for getting back. 

I've imported trilium-chat.js as js-frontend note in trilium with #run=frontendStartup  as inheritable label. 

When I reload, Chat_Options note and Chat_Prompts are there but when I reload, doesn't run or show prompt to enter API key - did I miss something else?

**Comment by soulsands** [comment]
> doesn't run or show prompt to enter API key - did I miss something else?
@mascooler 
Sorry, there is no UI available for configuring the API key. Options, including api key, should be written directly in the options note.  Thanks for the feedback, I have added more details on the documentation. 
BTW, the ` #run=frontendStartup` label doesn't need to be inheritable,

**Comment by mascooler** [comment]
Got it - I've added API key and reloaded but nothing comes up after that. Do any other files need to be imported from the code file?

![image](https://github.com/soulsands/trilium-chat/assets/102939756/0ad4dbcb-94d8-436f-afbb-f1d5fde6f741)

**Comment by soulsands** [comment]
alt+q is the default shortcut to toggle the UI， or you can click the chat icon on top right corner

**Comment by mascooler** [comment]
Amazing! Missed that, thanks for the clarification. Might be worth adding a point on that in the start instructions?

**Comment by soulsands** [comment]
>  Might be worth adding a point on that in the start instructions?

Okay, this point has already been addressed. Any suggestions would be appreciated, please feel free to give me feedback. :)

**Comment by mascooler** [comment]
Yeah I think point #5 in the start instructions is perfect, completely overlooked it. Great idea and implementation, look forward to seeing how it develops. Thanks - mc
