### ISSUE TITLE
API key error

### ISSUE THREAD

**Issue by radhesh1** [soulsands/trilium-chat#6]
I followed the steps but the it shows api key error

**Comment by soulsands** [comment]
Hi, could you provide more information? Where does the error come from?

**Comment by radhesh1** [comment]
So i did the whole process that you have mentioned at last it gives me the error of api key while testing it

**Comment by soulsands** [comment]
sorry，I can't reproduce the error.would you help provide the logs or screenshots?

**Comment by radhesh1** [comment]
I just followed your gitpod and did the steps got a api key from ChatGPT put it in then pressed verify and test

**Comment by soulsands** [comment]
Sorry I can't reproduce the error and it works fine for other people. Could you post a screenshot that shows the error? @radhesh1

**Comment by radhesh1** [comment]
![image](https://github.com/soulsands/trilium-chat/assets/70819367/4e65fd95-6dd7-44d5-bc8c-02ac0b22b1bf)

**Comment by radhesh1** [comment]
i think this might be a chatgpt quota issue

**Comment by TheBig-O** [comment]
Is it possible to use other chatbots? With the API quota for ChatGPT, you quickly run out of tokens.
Thanks for putting this together. I'm eager to give this a try.

**Comment by perfectra1n** [comment]
@TheBig-O you can use whatever models you want from OpenAI - the way the widget interacts with the API is specific to OpenAI's APIs, so you can just change to another model if you want.

**Comment by TheBig-O** [comment]
That's what I was thinking. Thanks for putting this together.
